# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build ESAPI Script - v16.1

on:
  workflow_dispatch:
    inputs:
      dateInput:
        description: 'Expiration Date'
        required: true
        default: '6/1/2025'

jobs:
  build:
    name: Build ESAPI Script - v16.1
    runs-on: windows-2019
    env:
      GITHUB_WORKSPACE_PACKAGES_PATH: packages\ESAPI.16.1.0\lib\net461\
      PROJECT_NAME: DoseRateEditor
      MAJOR_VERSION: 1
      MINOR_VERSION: 0
      PATCH_VERSION: 0
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Get Current Date
      id: currentDate
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "MM/DD/YYYY"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Update Target Framework Version to 4.6.1
      uses: Nambers/ReplaceStringInFile@v1.1
      with:
        path: .\${{ env.PROJECT_NAME}}\${{ env.PROJECT_NAME}}.csproj
        oldString: "TargetFrameworkVersion>v[\\d\\.]+<"
        newString: 'TargetFrameworkVersion>v4.6.1<'

    - name: Update AssemblyInfo.cs
      id: update_assembly_info
      run: |
        .\.github\workflows\Update-AssemblyInfo.ps1 `
          -AssemblyInfoFilePath .\${{ env.PROJECT_NAME}}\Properties\AssemblyInfo.cs `
          -ExpirationDate "${{ github.event.inputs.dateInput }}" `
          -BuildNumber ${{ env.BUILD_NUMBER }} `
          -ProjectName ${{ env.PROJECT_NAME }}

    - name: Download nuget packages
      run: nuget install .\${{ env.PROJECT_NAME}}\packages.config -OutputDirectory ${{ env.PROJECT_NAME}}\packages

    - name: Add VIC GitHub NuGet repository
      run: nuget source add `
        -Name github `
        -Source "https://nuget.pkg.github.com/Varian-MedicalAffairsAppliedSolutions/index.json" `
        -UserName craman96 `
        -Password ${{ secrets.GITHUB_TOKEN }} `
        -StorePasswordInClearText

    - name: Download ESAPI package
      run: nuget install ESAPI -Version 16.1.0 -OutputDirectory ${{ env.PROJECT_NAME}}\packages


    - name: Update hint paths in the csproj file
      run: |
        .\.github\workflows\Update-EsapiHintPaths.ps1 `
        -CsprojFilePath .\${{ env.PROJECT_NAME}}\ `
        -CsprojFileName ${{ env.PROJECT_NAME}}.csproj

    - name: Build Solution
      run: msbuild.exe .\${{ env.PROJECT_NAME}}.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Debug"

    - name: Zip
      run: |
        Compress-Archive `
          -Path ".\${{ env.PROJECT_NAME}}\bin\Debug\*" `
          -DestinationPath "${{ github.workspace }}/${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV161.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.9
      with:
        name: ${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV16.1
        tag_name: ${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV16.1
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        body: |
          This is an official release of the **`${{ env.PROJECT_NAME }}`** project.
          Supported Eclipse version: `v16.1`.
          The generated dll is valid until `${{ github.event.inputs.dateInput }}`, and generated on `${{ steps.currentDate.outputs.time }}`.
        files: ${{ github.workspace }}/${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV161.zip
